services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
      - redis
  
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=achievement_tracker
  
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  frontend_node_modules: