# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-test:5432/achievement_tracker_test
      - REDIS_URL=redis://redis-test:6379/0
      - TESTING=True
    depends_on:
      - postgres-test
      - redis-test
    command: >
      sh -c "python -m pytest tests/ --cov=app -v"
    
  frontend-test:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - CI=true
    command: npm test
    
  postgres-test:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=achievement_tracker_test
    tmpfs:
      - /var/lib/postgresql/data
      
  redis-test:
    image: redis:alpine
    tmpfs:
      - /data
